# Generated by Django 5.2.17 on 2026-08-07 12:20

import cases.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpposingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('employer', 'İşveren'), ('company', 'Şirket'), ('person', 'Gerçek kişi'), ('public', 'Kamu kurumu'), ('other', 'Diğer')], default='employer', max_length=20, verbose_name='Taraf türü')),
                ('name', models.CharField(max_length=255, verbose_name='Ad / unvan')),
                ('tax_identity_number', models.CharField(blank=True, max_length=30, verbose_name='Vergi / kimlik no')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='İrtibat kişisi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('lawyer_info', models.TextField(blank=True, verbose_name='Vekil bilgisi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Karşı taraf',
                'verbose_name_plural': 'Karşı taraflar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'T.C. kimlik numarası 11 rakam olmalıdır.')], verbose_name='T.C. kimlik no')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum tarihi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Görevi / unvanı')),
                ('employment_start', models.DateField(blank=True, null=True, verbose_name='İşe giriş tarihi')),
                ('employment_end', models.DateField(blank=True, null=True, verbose_name='İşten çıkış tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Genel notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'İşçi',
                'verbose_name_plural': 'İşçiler',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Aşama adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sıra')),
                ('color', models.CharField(choices=[('slate', 'Gri'), ('blue', 'Mavi'), ('amber', 'Sarı'), ('orange', 'Turuncu'), ('purple', 'Mor'), ('indigo', 'Lacivert'), ('green', 'Yeşil'), ('red', 'Kırmızı')], default='slate', max_length=20, verbose_name='Renk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Son aşama')),
            ],
            options={
                'verbose_name': 'Süreç aşaması',
                'verbose_name_plural': 'Süreç aşamaları',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=cases.models.generate_reference_number, editable=False, max_length=30, unique=True, verbose_name='Dosya no')),
                ('subject', models.CharField(max_length=255, verbose_name='Dosya konusu')),
                ('case_type', models.CharField(choices=[('labor', 'İşçilik alacağı'), ('reinstatement', 'İşe iade'), ('mediation', 'Arabuluculuk'), ('enforcement', 'İcra'), ('other', 'Diğer')], default='labor', max_length=30, verbose_name='Dosya türü')),
                ('court', models.CharField(blank=True, max_length=255, verbose_name='Mahkeme / merci')),
                ('court_file_number', models.CharField(blank=True, max_length=100, verbose_name='Mahkeme dosya no')),
                ('opening_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Açılış tarihi')),
                ('next_deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='Sonraki kritik tarih')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Kapanış tarihi')),
                ('summary', models.TextField(blank=True, verbose_name='Dosya özeti')),
                ('agreed_monthly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Aylık ücret')),
                ('severance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Kıdem tazminatı')),
                ('notice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='İhbar tazminatı')),
                ('other_receivables', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Diğer alacaklar')),
                ('financial_notes', models.TextField(blank=True, verbose_name='Finansal notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('responsible_lawyer', models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_case_files', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu avukat')),
                ('opposing_parties', models.ManyToManyField(related_name='case_files', to='cases.opposingparty', verbose_name='Karşı taraflar')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_files', to='cases.worker', verbose_name='İşçi')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_files', to='cases.workflowstage', verbose_name='Güncel aşama')),
            ],
            options={
                'verbose_name': 'İşçi dosyası',
                'verbose_name_plural': 'İşçi dosyaları',
                'ordering': ('-updated_at',),
                'permissions': [('view_financial_data', 'Finansal bilgileri görüntüleyebilir'), ('change_financial_data', 'Finansal bilgileri değiştirebilir'), ('view_all_casefiles', 'Tüm avukatların dosyalarını görüntüleyebilir'), ('transition_casefile', 'Dosya aşamasını değiştirebilir')],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('petition', 'Dilekçe'), ('evidence', 'Delil / belge'), ('decision', 'Karar'), ('expert', 'Bilirkişi raporu'), ('correspondence', 'Yazışma'), ('other', 'Diğer')], default='other', max_length=30, verbose_name='Belge türü')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('file', models.FileField(upload_to=cases.models.document_upload_path, verbose_name='Dosya')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.casefile', verbose_name='Dosya')),
            ],
            options={
                'verbose_name': 'Dosya belgesi',
                'verbose_name_plural': 'Dosya belgeleri',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Not')),
                ('is_private', models.BooleanField(default=False, verbose_name='Yalnızca sorumlu avukat ve yöneticiler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Yazan')),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.casefile', verbose_name='Dosya')),
            ],
            options={
                'verbose_name': 'Dosya notu',
                'verbose_name_plural': 'Dosya notları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Geçiş notu')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Değişiklik zamanı')),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='cases.casefile', verbose_name='Dosya')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_stage_changes', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_as_source', to='cases.workflowstage', verbose_name='Önceki aşama')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_as_target', to='cases.workflowstage', verbose_name='Yeni aşama')),
            ],
            options={
                'verbose_name': 'Aşama geçmişi',
                'verbose_name_plural': 'Aşama geçmişi',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Geçiş adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='cases.workflowstage', verbose_name='Başlangıç aşaması')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='cases.workflowstage', verbose_name='Hedef aşama')),
            ],
            options={
                'verbose_name': 'Süreç geçişi',
                'verbose_name_plural': 'Süreç geçişleri',
                'ordering': ('from_stage__order', 'to_stage__order'),
                'constraints': [models.UniqueConstraint(fields=('from_stage', 'to_stage'), name='unique_workflow_transition'), models.CheckConstraint(condition=models.Q(('from_stage', models.F('to_stage')), _negated=True), name='workflow_transition_different_stages')],
            },
        ),
    ]
